In [7]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
dir = '/content/drive/MyDrive/Learn/Platzi/DataScience/Pandas/db/{}'.format('chipotle.tsv')

In [11]:
df = pd.read_csv(dir, '\t')
df

      order_id  ...  item_price
0            1  ...      $2.39
1            1  ...      $3.39
2            1  ...      $3.39
3            1  ...      $2.39
4            2  ...     $16.98
...        ...  ...         ...
4617      1833  ...     $11.75
4618      1833  ...     $11.75
4619      1834  ...     $11.25
4620      1834  ...      $8.75
4621      1834  ...      $8.75

[4622 rows x 5 columns]

##Show the first 10 entries

In [12]:
chipo = df
chipo.head(10)

   order_id  ...  item_price
0         1  ...      $2.39
1         1  ...      $3.39
2         1  ...      $3.39
3         1  ...      $2.39
4         2  ...     $16.98
5         3  ...     $10.98
6         3  ...      $1.69
7         4  ...     $11.75
8         4  ...      $9.25
9         5  ...      $9.25

[10 rows x 5 columns]

#What is the Number of Observations for Dataset

In [13]:
#Solution 1
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

In [14]:
#Solution 2
chipo.shape
#It returns the size of an array

(4622, 5)

In [33]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

##Which was the most-ordered Item?

In [31]:
item_quants = chipo.groupby(['item_name']).agg({'quantity':'sum'})
item_quants.sort_values('quantity',ascending=False)[:5]

                     quantity
item_name
Chicken Bowl              761
Chicken Burrito           591
Chips and Guacamole       506
Steak Burrito             386
Canned Soft Drink         351

##what was the most-ordered item in the choice_description

In [36]:
item_quants = chipo.groupby(['choice_description']).agg({'quantity':'sum'})
item_quants.sort_values('quantity',ascending=False)[:5]

                                                    quantity
choice_description
[Diet Coke]                                              159
[Coke]                                                   143
[Sprite]                                                  89
[Fresh Tomato Salsa, [Rice, Black Beans, Cheese...        49
[Fresh Tomato Salsa, [Rice, Black Beans, Cheese...        42

##How many items were ordered in total?

In [38]:
chipo.quantity.sum()

4972

## Turn the item price into a float

In [ ]:
chipo['item_price'] = chipo.item_price.str.slice(1).astype(float)

##How much was the revenue for the period in the dataset?

In [46]:
revenue = chipo.item_price.sum()
revenue

34500.16

##How many orders were made in this period?

In [50]:
orders = chipo.order_id.count()
orders

4622

##What is the average revenue amount per order?

In [53]:
average = chipo['item_price'].mean()
average

7.464335785374397

##How  many different items were ordered?

In [55]:
chipo.item_name.nunique()

50